{{- if .Values.containerService }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster_service_ready
rules:
  - nonResourceURLs: ["/readyz", "/readyz/*"]
    verbs: ["get"]
{{- end }}