    {{- if .Values.containerService }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: container_role_binding
subjects:
- kind: ServiceAccount
  name: {{ include "xnat.serviceAccountName" . }}
roleRef:
  kind: Role
  name: container_role
  apiGroup: rbac.authorization.k8s.io
{{- end }}