{{- if .Values.createConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat.fullname" . }}
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat.postgresql.postgresqlUri" . }}/{{ template "xnat.postgresql.postgresqlDatabase" . }}
    datasource.username={{ template "xnat.postgresql.postgresqlUsername" . }}
    datasource.password={{ template "xnat.postgresql.postgresqlPassword" . }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
{{- if .Values.activemq.broker.enabled }}
    spring.activemq.broker-url=tcp://activemq-artemis-{{ template "xnat.fullname" . }}-0-svc:62626
    spring.activemq.user={{ template "xnat.activemq.username" . }}
    spring.activemq.password={{ template "xnat.activemq.password" . }}
{{- end }}
{{- with .Values.extraConfig }}
{{- range $key, $value := . }}
    {{ $key }}={{ $value }}
{{- end }}
{{- end }}
{{- end }}
